export const countryNamesSe = {
  Austria: "Österrike",
  Belgium: "Belgien",
  Croatia: "Kroatien",
  Czech_Republic: "Tjeckien",
  Denmark: "Danmark",
  England: "England",
  North_Macedonia: "Makedonien",
  Finland: "Finland",
  France: "Frankrike",
  Germany: "Tyskland",
  Hungary: "Ungern",
  Italy: "Italien",
  Netherlands: "Nederländerna",
  Poland: "Polen",
  Portugal: "Portugal",
  Russia: "Ryssland",
  Scotland: "Skottland",
  Slovakia: "Slovakien",
  Spain: "Spanien",
  Sweden: "Sverige",
  Switzerland: "Schweiz",
  Turkey: "Turkiet",
  Ukraine: "Ukraina",
  Wales: "Wales",
};
